name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Pull latest image
        run: sudo docker pull vishnu3332/planner:latest

      - name: Stop old container
        run: sudo docker rm -f cicd-pipeline-container || true

      - name: Run new container
        run: sudo docker run -d    -p 5173:5173  -e JWT_SECRET=${{ secrets.JWT_SECRET }} --name cicd-pipeline-container vishnu3332/planner:latest